name: "31-33"

on:
  workflow_dispatch:
  schedule:
    - cron: '5 0,6,12,18 * * *'

jobs:
  run-bot:
    runs-on: ubuntu-latest
    timeout-minutes: 330
    strategy:
      fail-fast: false
      matrix:
        target: ['akun-31', 'akun-32', 'akun-33']

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install Google Chrome
      run: |
        sudo apt-get update
        sudo apt-get install -y wget google-chrome-stable

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install google-api-python-client google-auth-httplib2 google-auth-oauthlib selenium requests selenium-stealth undetected-chromedriver

    - name: Download & Extract Files from Google Drive
      env:
        GCP_SA_KEY: ${{ secrets.GCP_SA_KEY }}
        DRIVE_FOLDER_ID: ${{ secrets.DRIVE_FILE_ID }}
      run: python download_drive.py

    - name: Run All Subfolder Bots In Parallel
      run: |
        target="${{ matrix.target }}"
        echo "=== MENCARI SUBFOLDER DENGAN TARGET: $target ==="
        
        # Cari semua folder yang punya seofast_zhp.py & cocok dengan target
        find . -type f -name "seofast_zhp.py" | grep "$target" | while read -r script_path; do
          dir=$(dirname "$script_path")
          echo "==> Menjalankan Bot di: $dir"
          (
            cd "$dir" || exit
            until python3 seofast_zhp.py; do
              echo "[!] Bot di $dir terhenti (Exit Code: $?). Auto-restart dalam 5 detik..."
              sleep 5
            done
          ) &
        done

        # Tunggu semua background process bot selesai
        wait
